--- 
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata: 
  name: consul-leader
  namespace: kv
spec: 
  template: 
    metadata: 
      labels: 
        app: consul-leader
      annotations: 
        pod.beta.kubernetes.io/init-containers: >
            [
                {
                "name": "backup-restore",
                "image": "nebtex/backups",
                "imagePullPolicy": "Always",
                "env": [
                  {
                    "name": "APP_NAME",
                    "value": "consul"
                  },
                  {
                    "name": "NAMESPACE",
                    "valueFrom": {
                      "fieldRef": {
                        "fieldPath": "metadata.namespace"
                      }
                    }
                  },
                  {
                    "name": "POD_NAME",
                    "value": "consul-leader"
                  },
                  {
                    "name": "AWS_BUCKET",
                    "valueFrom": {
                      "secretKeyRef": {
                        "name": "consul-backup-credentials",
                        "key": "AWS_BUCKET"
                      }
                    }
                  },
                  {
                    "name": "AWS_BUCKET",
                    "valueFrom": {
                      "secretKeyRef": {
                        "name": "consul-backup-credentials",
                        "key": "AWS_BUCKET"
                      }
                    }
                  },
                  {
                    "name": "AWS_REGION",
                    "valueFrom": {
                      "secretKeyRef": {
                        "name": "consul-backup-credentials",
                        "key": "AWS_REGION"
                      }
                    }
                  },
                  {
                    "name": "AWS_ACCESS_KEY_ID",
                    "valueFrom": {
                      "secretKeyRef": {
                        "name": "consul-backup-credentials",
                        "key": "AWS_ACCESS_KEY_ID"
                      }
                    }
                  },
                  {
                    "name": "AWS_SECRET_ACCESS_KEY",
                    "valueFrom": {
                      "secretKeyRef": {
                        "name": "consul-backup-credentials",
                        "key": "AWS_SECRET_ACCESS_KEY"
                      }
                    }
                  },
                  {
                    "name": "BORG_PASSPHRASE",
                    "valueFrom": {
                      "secretKeyRef": {
                        "name": "consul-backup-credentials",
                        "key": "BORG_PASSPHRASE"
                      }
                    }
                  }
                ],
                "volumeMounts": [
                    {
                    "name": "consul-data",
                    "mountPath": "/vulumes/consul/data"
                    },
                    {
                    "name": "config-volume",
                    "mountPath": "/vulumes/consul/config"
                    }
                ]
                }
            ]
    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: consul-secrets
            items:
              - key: consul.json
                path: consul.json
                mode: 0777
        - name: consul-data
          emptyDir: {}
      containers: 
        - name: backups
          args:
          # backup each hour
          - 0 * * * *
          image: nebtex/backups
          imagePullPolicy: Always
          env:
          - name: APP_NAME
            value: consul
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            value: consul-leader
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: consul-backup-credentials
                key: AWS_BUCKET
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: consul-backup-credentials
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: consul-backup-credentials
                key: AWS_REGION
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: consul-backup-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: consul-backup-credentials
                key: AWS_SECRET_ACCESS_KEY
          - name: BORG_PASSPHRASE
            valueFrom:
              secretKeyRef:
                name: consul-backup-credentials
                key: BORG_PASSPHRASE               
        - args:
            - "consul"
            - "agent"
            - "-data-dir=/consul/data"
            - "-config-dir=/data/config"
            - "-server"
            - "-bootstrap"
            - "-datacenter"
            - "global"
            - "-ui"
            - "-client"
            - "0.0.0.0"
            - "-node"
            - "leader"
          image: "consul:0.7.3"
          imagePullPolicy: IfNotPresent
          name: consul-leader
          volumeMounts:
            - name: config-volume
              mountPath: /data/config
            - mountPath: /consul/data
              name: master-data
          ports:
            - containerPort: 8600
              name: dns-port
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: cli-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8300
              name: server
