apiVersion: v1
kind: Secret
metadata:
  name: consul-backup-credentials
  namespace: kv
data:
  AWS_BUCKET: ${AWS_BUCKET:?}
  AWS_REGION: ${AWS_REGION:?}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?}
  BORG_PASSPHRASE: ${BORG_PASSPHRASE:?}

