---
apiVersion: v1
kind: Service
metadata:
  name: consul 
  namespace: kv
  labels:
    app: consul
spec:
  clusterIP: None
  ports:
    # the port that this service should serve on
    - name: dns
      port: 8600
    - name: http
      port: 8500
    - name: rpc
      port: 8400
    - name: serflan
      port: 8301
    - name: serfwan
      port: 8302
    - name: server
      port: 8300
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: consul
