---
apiVersion: v1
kind: Service
metadata:
  name: consul 
  namespace: kv
  labels:
    app: consul
spec:
  clusterIP: None
  ports:
    # the port that this service should serve on
    - name: dns
      port: 8600
    - name: http
      port: 8500
    - name: rpc
      port: 8400
    - name: serflan
      port: 8301
    - name: serfwan
      port: 8302
    - name: server
      port: 8300
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: consul
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
  namespace: kv
spec:
  serviceName: consul
  replicas: 5
  template: 
    metadata: 
      labels: 
        app: consul
      annotations: 
          scheduler.alpha.kubernetes.io/affinity: >
              {
              "podAntiAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [{
                  "labelSelector": {
                    "matchExpressions": [{
                      "key": "app",
                      "operator": "In",
                      "values": ["consul"]
                    }]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }]
              }
            }
    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: consul-secrets
            defaultMode: 0777
      containers:
        - args:
            - "consul"
            - "agent"
            - "-data-dir=/consul/data"
            - "-config-dir=/data/config"
            - "-server"
            - "-datacenter"
            - "global"
            - "-ui"
            - "-client"
            - "0.0.0.0"
            - "-retry-join"
            - "consul-leader"
          image: "consul:0.7.2"
          imagePullPolicy: IfNotPresent
          name: consul-replica
          volumeMounts:
            - name: config-volume
              mountPath: /data/config
          ports:
            - containerPort: 8600
              name: dns-port
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: cli-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8300
              name: server