--- 
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata: 
  name: consul-replica-2
  namespace: kv
spec: 
  template: 
    metadata: 
      labels: 
        app: consul-replica-2
      annotations: 
          scheduler.alpha.kubernetes.io/affinity: >
              {
                "nodeAffinity": {
                    "requiredDuringSchedulingIgnoredDuringExecution": {
                      "nodeSelectorTerms": [
                        {
                          "matchExpressions": [
                            {
                              "key": "kv-store-replica-2",
                              "operator": "In",
                              "values": ["yes"]
                            }
                          ]
                        }
                      ]
                    }
                  }
              }
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: consul-client-config
        - name: master-data
          hostPath:
            # directory location on host
            path: /data/consul
      containers: 
        - args: 
            - "agent"
            - "-server"
            - "-bootstrap-expect"
            - "3"
            - "-datacenter"
            - "global"
            - "-ui"
            - "-client"
            - "0.0.0.0"
            - "-retry-join"
            - "consul-leader"
            - "-data-dir"
            - "/data/consul"
            - "-node"
            - "replica-2"
            - "-config-dir"
            - "/data/conf"
          image: "consul:0.7.2"
          imagePullPolicy: IfNotPresent
          name: consul-replica-2
          securityContext:
            privileged: true
          volumeMounts:
            - name: config-volume
              mountPath: /data/conf
            - mountPath: /data/consul
              name: master-data
          ports:
            - containerPort: 8600
              name: dns-port
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: cli-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8300
              name: server