--- 
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata: 
  name: consul-replica-3
  namespace: kv
spec: 
  template: 
    metadata: 
      labels: 
        app: consul-replica-3
      annotations: 
          scheduler.alpha.kubernetes.io/affinity: >
              {
                "nodeAffinity": {
                    "requiredDuringSchedulingIgnoredDuringExecution": {
                      "nodeSelectorTerms": [
                        {
                          "matchExpressions": [
                            {
                              "key": "kv-store-replica-3",
                              "operator": "In",
                              "values": ["yes"]
                            }
                          ]
                        }
                      ]
                    }
                  }
              }
    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: consul-secrets
            defaultMode: 0777
        - name: master-data
          hostPath:
            # directory location on host
            path: /data/consul
      containers:
        - args:
            - "consul"
            - "agent"
            - "data-dir=/consul/data"
            - "config-dir=/data/config"
            - "-server"
            - "-bootstrap-expect"
            - "3"
            - "-datacenter"
            - "global"
            - "-ui"
            - "-client"
            - "0.0.0.0"
            - "-retry-join"
            - "consul-leader"
            - "-node"
            - "replica-3"
          image: "consul:0.7.2"
          imagePullPolicy: IfNotPresent
          name: consul-replica-3
          volumeMounts:
            - name: config-volume
              mountPath: /data/config
            - mountPath: /consul/data
              name: master-data
          ports:
            - containerPort: 8600
              name: dns-port
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: cli-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8300
              name: server